version: '3'

services:
# database layer  
  db:
    build:
      context: ./database
    image: mysql:5
    restart: always
    env_file: 
      - ./database/.env
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - "./database/mysql:/var/lib/mysql:rw"
      - ./database/a-customers-seeds.sql:/docker-entrypoint-initdb.d/a-customers-seeds.sql
      - ./database/b-orders-seeds.sql:/docker-entrypoint-initdb.d/b-orders-seeds.sql
# backend layer
  backend:
    build:
      context: ./backend
    env_file: 
      - ./backend/.env
    expose: 
      - "3001"
    ports:
      - "3420:3001"
    volumes:
      - ./backend/src:/home/backend/src
      - ./backend/sequelize/config:/home/backend/sequelize/config
      - ./backend/sequelize/migrations:/home/backend/sequelize/migrations
      - ./backend/sequelize/seeders:/home/backend/sequelize/seeders
    depends_on:
      - db
# frontend layer      
  frontend:
      build:
        context: ./frontend
      env_file: 
        - ./frontend/.env
      expose: 
        - "3000"
      ports:
        - "80:3000"
      volumes:
        - ./frontend/src:/home/frontend/src